In [24]:
import requests
import pandas as pd

demo= 'e46f1a303dafb62460de104424a00084'
company = 'AAPL'
quarter = 3
year = 2020

transcript = requests.get(f'https://financialmodelingprep.com/api/v3/earning_call_transcript/{company}?quarter={quarter}&year={year}&apikey={demo}').json()

transcript = transcript[0]['content'].split('\n')
pd.DataFrame(transcript)
### Problem, this method does not exclude questions. ###

                                                    0
0   Operator: Good day, everyone. Welcome to the A...
1   Tejas Gala: Thank you. Good afternoon and than...
2   Tim Cook: Thanks, Tejas. Good afternoon, every...
3   Luca Maestri: Thank you, Tim. Good afternoon, ...
4   Tejas Gala: Thank you, Luca. We ask that you l...
..                                                ...
66  Wamsi Mohan: Okay. Thanks, Tim. And as a follo...
67  Tim Cook: Well, I don't want to make a forever...
68                          Wamsi Mohan: Thanks, Tim.
69  Tejas Gala: Thank you, Wamsi. A replay of toda...
70  Operator: And again, that will conclude today'...

[71 rows x 1 columns]

In [79]:
def call_pull(ticker, year, quarter,key = 'e46f1a303dafb62460de104424a00084'):
    transcript = requests.get(f'https://financialmodelingprep.com/api/v3/earning_call_transcript/{ticker}?quarter={quarter}&year={year}&apikey={demo}').json()
    transcript = transcript[0]['content']
    return transcript

def entire_report_pull(stock_list, year_list, quarter_list):
    report = []
    columns = []
    for stock in stock_list:
        stonks = []
        for yr in year_list:
            for qtr in quarter_list:
                if f'{yr},{qtr} Qtr' not in columns:
                    columns.append(f'{yr},{qtr} Qtr')
                try:
                    stonks.append(call_pull(stock, yr, qtr))
                except IndexError:
                    stonks.append(None)
        report.append(stonks)
    return pd.DataFrame(report, columns = columns, index = stock_list)


def labels(stock_list, year_list, quarter_list):
    

test_tech = ['AAPL','AMZN']
test_quarters= [1,2,3,4]
test_years = [2019,2020]

In [80]:
pd.DataFrame(entire_report_pull(test_tech, test_years, test_quarters))

,"2019,1 Qtr","2019,2 Qtr","2019,3 Qtr","2019,4 Qtr","2020,1 Qtr","2020,2 Qtr","2020,3 Qtr","2020,4 Qtr"
AAPL,Operator: Good day and welcome to the Apple In...,"Operator: Good day, and welcome to the Apple I...","Operator: Good day, and welcome to the Apple I...","Operator: Good day, everyone. Welcome to the A...","Operator: Good day, everyone. Welcome to the A...",Operator: Good day everyone. Welcome to the Ap...,"Operator: Good day, everyone. Welcome to the A...",Operator: Good day everyone and welcome to th...
AMZN,"Operator: Thank you for standing by. Good day,...","Operator: Thank you for standing by. Good day,...",Operator: Thank you for standing by. Good day ...,"Operator: Thank you for standing by. Good day,...",Operator: Good day everyone and welcome to the...,Operator: Thank you for standing by. Good day...,None,None

In [17]:
### List of Micro to Large United States Technology Companies listed on the NASDAQ ###
### Companies with Market Cap of $50M - $200B ###
tech = ['AAOI','ABST','ACAC','ACEV','ACIW','ACLS','ACMR',
'ADI','ADP','ADSK','AEYE','AGYS','AIRG','ALGM','ALOT',
'ALRM','ALTR','ALYA','AMAT','AMBA','AMD','AMKR','AMST',
'AMSWA','ANSS','APPF','APPN','APXT','ASUR','ASYS','ATOM',
'ATVI','AVCT','AVGO','AVID','AVNW','AVT','AWRE','AXTI',
'AZPN','BAND','BBSI','BCOV','BEEM','BIGC','BL','BLKB',
'BMBL','BNFT','BRKS','BSY','BTRS','CAMP','CARG','CASA',
'CCMP','CCRN','CDLX','CDNS','CERN','CERT','CEVA','CHNG',
'CHX','CLSK','CMTL','COMM','COUP','CPSI','CREE','CRNC',
'CRSR','CRUS','CRWD','CSGS','CSOD','CTG','CTSH','CTXS',
'CVLT','CYRN','DBX','DCBO','DCT','DDOG','DGII','DGLY',
'DIOD','DLHC','DMRC','DOCU','DOMO','DRTT','DSGX','DSP',
'DSPG','EA','EBIX','EGAN','ELYS','EMKR','ENPH','ENVB',
'EPAY','ERII','ESSC','EVBG','EVER','EXTR','FEYE','FFIV',
'FISV','FIVN','FORM','FPAY','FROG','FSLR','FSRV','FTNT',
'GDRX','GDYN','GEG','GFN','GLUU','GNOG','GRPN','GSIT',
'GTYH','HCAT','HLIT','HQI','HSII','HSTM','ICHR','IDN',
'IEC','IMMR','INOD','INOV','INPX','INSE','INTU','INTZ',
'INVE','IPGP','IPHI','ISSC','ISUN','IVAC','JAMF','JCOM',
'JKHY','KBNT','KE','KELYA','KELYB','KERN','KFRC','KOPN',
'KTCC','KVHI','LASR','LCY','LECO','LOGI','LORL','LPSN',
'LPTH','LRCX','LSCC','LTRPA','LTRPB','LTRX','MANH','MARA',
'MCFE','MCHP','MDB','MDCA','MDRX','MGNI','MGRC','MIDD',
'MITK','MNTX','MPWR','MRAM','MSGM','MSTR','MTBC','MTCH',
'MTSI','MU','MXIM','NATI','NCNO','NETE','NH','NLOK',
'NTAP','NTCT','NTNX','NUAN','NVEC','NXGN','OBLG','OEG',
'OKTA','OMCL','ON','ONDS','OSIS','OSPN','OSS','OTEX',
'PCTI','PCTY','PCYG','PDFS','PEGA','PFPT','PIXY','PLAB',
'PLUS','PLXS','POWI','PRCH','PRFT','PRGS','PS','PTC',
'PUBM','PXLW','QADA','QADB','QCOM','QLYS','QMCO','QRHC',
'QRVO','QUIK','QUMU','RBBN','RCII','RDVT','RELL','RESN',
'RIOT','RMBL','RMBS','RNWK','RP',
'RPD','RXT','SABR','SANM','SCKT','SCPL','SCSC','SCWX',
'SEAC','SGH','SGMS','SHLS','SHSP','SITM','SLAB','SLP',
'SMCI','SMSI','SMTC','SMTX','SNCR','SNPS','SPLK','SPRT',
'SPSC','SPT','SPWR','SRAX','SSNC','SSPK','SSTI','SSYS','STRM',
'SUMO','SVMK','SWIR','SWKS','SYKE','SYNA','SYNC','TACT',
'TCX','TENB','TESS','TLS','TRIP','TRUE','TTD','TTEC',
'TTMI','TTWO','TWIN','TWOU','TXN','UCTT','UPLD','UPWK',
'VECO','VERI','VERX','VIAV','VIH','VOXX','VRNS','VRNT',
'VRSK','VRSN','VS','VSAT','VUZI','WATT','WDAY','WDC',
'WSTG','XLNX','XM','XPER','ZBRA','ZI','ZIXI','ZM','ZNGA','ZS']